name: 'Setup and Cleanup Provisioned Concurrency for AWS Lambda'
description: 'Sets up provisioned concurrency for a specified AWS Lambda function and cleans up older versions'
author: 'IronCloud'
branding:
  color: orange
  icon: arrow-up-right
inputs:
  function-name:
    description: 'Name of the AWS Lambda function'
    required: true
  provisioned-concurrency:
    description: 'Number of provisioned concurrency'
    required: true
  api-id:
    description: 'ID of API'
    required: false
  stage-name:
    description: 'Name of Stage'
    required: false
    default: 'dev'
    type: string
outputs:
  new-version:
    description: 'The new version number of the Lambda function'
  provisioned-concurrency:
    description: 'The provisioned concurrency count that was set'
  function-name-full: 
    description: 'The lambda function name with version if it exists'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/src/entrypoint.sh
      shell: bash
      env:
        INPUT_FUNCTION_NAME: ${{ inputs.function-name }}
        INPUT_PROVISIONED_CONCURRENCY: ${{ inputs.provisioned-concurrency }}
        INPUT_API_ID: ${{ inputs.api-id }}
        INPUT_STAGE_NAME: ${{ inputs.stage-name }}
